### PR TITLE
change rm -> rm -f

### PR DESCRIPTION
**Pull request by AndyLHCb**

### CODE REVIEW

**Comment by alexpearce** [comment]
What's the motivation here? Plain `rm` should be OK.

**Comment by AndyLHCb** [comment]
The motivation is that in my uni (Warwick) and possibly some others, by default the .bashrc sets `alias rm='rm -i'`, by changing this to `rm -f` we get the same behavior even if this is the case.

**Comment by alexpearce** [comment]
I alias `rm` to `rm -i` as well, but I don't think this affects the _behaviour_ of the snippet.

```
$ touch tmp
$ rm -i tmp && echo y
remove tmp? y
y
```

Having to respond to the question seems reasonable to me.

**Comment by klieret** [comment]
Hi @AndyLHCb : Thanks again for your suggestion and creating a PR. As @chrisburr's point seems to be valid and there hasn't been any further activity, let me close this.

**Pull request closed without merging**
