### PR TITLE
snakemake: how to list dependencies

### PR DESCRIPTION
**Pull request by goi42**
Inspired by a question during the 2021 Starterkit, this PR adds a digression on what files to list as dependencies.

### CODE REVIEW

**Comment by goi42** [comment]
The build seems to have failed due to issues unrelated to this PR.

**Comment by vlukashenko** [comment]
> The build seems to have failed due to issues unrelated to this PR.

Yes, it looks like @jonas-eschle has fixed this error from the advanced python on the master? Anyway, this PR indeed shouldn't create any problems.

**Comment by jonas-eschle** [comment]
Hm, this is annoying, it's really a bug then... this happens when the data cannot be downloaded. I first thought it was a temp glitch, because it started to pass again, but failing now is a bit weird... Restarting should solve the problem for now, but I'll have a closer look to it!

Many thanks for the PR!

**Comment by vlukashenko** [comment]
> Hm, this is annoying, it's really a bug then... this happens when the data cannot be downloaded. I first thought it was a temp glitch, because it started to pass again, but failing now is a bit weird... Restarting should solve the problem for now, but I'll have a closer look to it!
> 
> Many thanks for the PR!

Thanks!

**Pull request merged**
