### PR TITLE
add/update tutorials, advancedPython, inference notebook

### PR DESCRIPTION
**Pull request by mayou36**
Switch to uproot4
add advanced Python tutorial with context manager, decorator and (un)packing
add inference (sceleton) to talk about model fitting and inference

### CODE REVIEW

**Comment by chrisburr** [comment]
You need to add the new deps to https://github.com/hsf-training/analysis-essentials/blob/master/environment.yml

**Comment by mayou36** [comment]
Hm, `OSError: remote server does not support HTTP range requests` seems to happen with `uproot4` , [opened an issue](https://github.com/scikit-hep/uproot4/issues/176)

**Comment by mayou36** [comment]
This is finished except of the mentioned bug in uproot4.

Added also a small Scikit-HEP tutorial with `particles`, `hepunits`, `formulate`
Added the sPlot calculation with `hepstats`
Added the advanced Python with exceptions, context manager, etc
Updated README with an overview
and extended some of the tutorials slightly

**Comment by mayou36** [comment]
This fails currently due to uproot4 new version not yet released. As soon as >0.1.2 is out, this should work.

**Comment by mayou36** [comment]
Needs https://github.com/hsf-training/analysis-essentials/pull/23 to get merged

**Comment by mayou36** [comment]
@chrisburr can we merge this maybe?

**Comment by mayou36** [comment]
@eduardo-rodrigues can this maybe be merged? And if there is a lack of maintainers to keep it up to date, I would volunteer to become one

**Comment by chrisburr** [comment]
Sorry for not getting to this. You should have an invite with merge rights for this repository.

One comment: Can you remove the output from the notebooks to avoid inflating the repository? They should be added by the CI for the actual webpage.

**Comment by eduardo-rodrigues** [comment]
(OK, @chrisburr already replied / did it all :-).)

**Comment by mayou36** [comment]
Many thanks, sorry for double pinging, and yes, I'll remove the output

**Comment by mayou36** [comment]
Removed the outputs, all working now, merging

**Pull request merged**
