### PR TITLE
Snakemake

### PR DESCRIPTION
**Pull request by goi42**
Adds Snakemake lesson, since it is being incorporated into the Starterkit.

The lesson is based on that from second-analysis-steps [here](https://github.com/goi42/starterkit-lessons/blob/dc2c5deb46eaee7b9bc75a7cd6bc1347632fe791/second-analysis-steps/analysis-automation-snakemake.md),
but it has been heavily modified to be more accessible to beginners.

Some information has been dropped, namely, descriptions of `expand` and `directory` and the use of python functions as input. The section on reports has been commented-out, as it needs substantial re-writes to function as a tutorial. Some information has also been added.

### CODE REVIEW

**Comment by goi42** [comment]
I should say that the instructions to build locally in the [contributing guidelines](https://github.com/hsf-training/analysis-essentials/blob/dad8cff5957562b8ab1386d2e67ef37819a39751/CONTRIBUTING.md) do not work, so I have not been able to properly test these changes.

___
I get an error:
```text
Notebook error:
NoSuchKernel in advanced-python/10Basics.ipynb:
No such kernel named python3
Traceback (most recent call last):
  File "/Users/michael/opt/anaconda3/envs/Starterkit_simple/bin/starterkit_ci", line 8, in <module>
    sys.exit(parse_args())
  File "/Users/michael/opt/anaconda3/envs/Starterkit_simple/lib/python3.10/site-packages/starterkit_ci/__init__.py", line 33, in parse_args
    known_commands[args.command](
  File "/Users/michael/opt/anaconda3/envs/Starterkit_simple/lib/python3.10/site-packages/starterkit_ci/__init__.py", line 44, in build_docs
    _sphinx_build('html', source_dir, allow_warnings)
  File "/Users/michael/opt/anaconda3/envs/Starterkit_simple/lib/python3.10/site-packages/starterkit_ci/__init__.py", line 82, in _sphinx_build
    return check_call(cmd, cwd=source_dir)
  File "/Users/michael/opt/anaconda3/envs/Starterkit_simple/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sphinx-build', '-M', 'html', '.', 'build']' returned non-zero exit status 2.
```
This is not the case for the [Starterkit](https://github.com/lhcb/starterkit-lessons/blob/ea15ff354b1c216f2562f432aa3a71f6f2408666/CONTRIBUTING.md), which deploys just fine.

**Comment by vlukashenko** [comment]
> I should say that the instructions to build locally in the [contributing guidelines](https://github.com/hsf-training/analysis-essentials/blob/dad8cff5957562b8ab1386d2e67ef37819a39751/CONTRIBUTING.md) do not work, so I have not been able to properly test these changes.
> 
> I create a conda environment using a yaml file:
> 
> ```yaml
> name: Starterkit
> channels:
>   - conda-forge
>   - defaults
> dependencies:
> # - starterkit-ci
>   - matplotlib
>   - uproot
>   - numpy
>   - pandas
>   - root_pandas
>   - scipy
>   - tensorflow
>   - xgboost
> ```
> 
> I then activate it and call `pip install starterkit-ci`.
> 
> `starterkit_ci build --allow-warnings` leads to:
> 
> ```
> Notebook error:
> NoSuchKernel in advanced-python/10Basics.ipynb:
> No such kernel named python3
> Traceback (most recent call last):
>   File "/Users/michael/opt/anaconda3/envs/Starterkit_simple/bin/starterkit_ci", line 8, in <module>
>     sys.exit(parse_args())
>   File "/Users/michael/opt/anaconda3/envs/Starterkit_simple/lib/python3.10/site-packages/starterkit_ci/__init__.py", line 33, in parse_args
>     known_commands[args.command](
>   File "/Users/michael/opt/anaconda3/envs/Starterkit_simple/lib/python3.10/site-packages/starterkit_ci/__init__.py", line 44, in build_docs
>     _sphinx_build('html', source_dir, allow_warnings)
>   File "/Users/michael/opt/anaconda3/envs/Starterkit_simple/lib/python3.10/site-packages/starterkit_ci/__init__.py", line 82, in _sphinx_build
>     return check_call(cmd, cwd=source_dir)
>   File "/Users/michael/opt/anaconda3/envs/Starterkit_simple/lib/python3.10/subprocess.py", line 369, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['sphinx-build', '-M', 'html', '.', 'build']' returned non-zero exit status 2.
> ```
> 
> This is not the case for the [Starterkit](https://github.com/lhcb/starterkit-lessons/blob/ea15ff354b1c216f2562f432aa3a71f6f2408666/CONTRIBUTING.md), which deploys just fine.
> 
> macOS Monterey Version 12.0.1 conda 4.10.3 pip 12.1.3 python 3.8.6

Hi, Michael! Thank you for taking care of the snakemake lesson. I think that the error you see comes from the fact that you forgot to add jupyterlab to your environment. analysis-essentials contain a lot of python notebooks, so the jupyterlab is necessary to run it. If you want to test this locally it's probably easier to build the environment using [environment.yml](https://github.com/hsf-training/analysis-essentials/blob/master/environment.yml).

**Comment by vlukashenko** [comment]
Okay I found issues with some links, but it is not connected to the snakemake lesson anyway. There is one important suggestion from Chris Burr, to move the `lb-conda` to the pop-out window. I will do it myself in a separate commit to save your time.

**Comment by goi42** [comment]
@vlukashenko Thanks! I have requested #31 to incorporate my updates after seeing the built website.

I have also requested #30 to clarify the environment setup for future contributors.

**Pull request merged**
