### PR TITLE
making it runnable

### PR DESCRIPTION
**Pull request by JuanBSLeite**

### CODE REVIEW

**Comment by mayou36** [comment]
Hi, many thanks! However, I am not sure I understand the PR, what exactly did you change? It's hard to see the notebook diffs

**Comment by JuanBSLeite** [comment]
Hi, I changed the version of uproot to 4 and the way it formats the array to pandas using awkward.to_pandas(array) method.


 The actual code is crashing in this line:
```
data = uproot.open('https://cern.ch/starterkit/data/advanced-python-2019/dalitzdata.root',
                   httpsource={'chunkbytes': 1024*1024, 'limitbytes': 33554432, 'parallel': 64})['tree'].pandas.df()
```

I changed to:
```
data = uproot4.open('https://cern.ch/starterkit/data/advanced-python-2019/dalitzdata.root',
                   httpsource={'chunkbytes': 1024*1024, 'limitbytes': 33554432, 'parallel': 64})['tree']

data =data.arrays(data.keys())
data = ak.to_pandas(data)
```
and now it's running.

**Comment by mayou36** [comment]
Okay many thanks, but this is already addressed in #23, it's unfortunately not yet merged.

So maybe you can close this PR, the other one should be merged anytime I assume

**Comment by JuanBSLeite** [comment]
This is the way I found to fix the crashing haha. But ok, I'll close this PR. 

Thank you!

**Pull request closed without merging**
