### PR TITLE
fix: remove unparsed markdown from copyright footer

### LINKED ISSUE #61: Broken copyright footer
Probably neither accurate, nor does it render well... 

https://github.com/hsf-training/analysis-essentials/blob/0ac66759a9d30b03d8e478128f1f48b6f9ed7800/conf.py#L6

image

### PR DESCRIPTION
**Pull request by wdconinc**
Fixes #61. This doesn't aim to resolve the underlying copyright question pointed out in #61 (@klieret, what's "not accurate" about it?), but it fixes the parsing issue.

### CODE REVIEW

**Review by klieret — APPROVED** [review]

**Comment by klieret** [comment]
Ah, regarding the "not accurate", I don't see anything that is based off of the carpentries (neither content nor framework), but I guess it says "originally". Anyway, doesn't matter :)

**Comment by klieret** [comment]
I'll leave this for @jonas-eschle to merge :)

**Comment by wdconinc** [comment]
As far as I can tell, the content of the git lesson is based on git-novice originally, making this a derived work. Someone went through and turned it from md to rst for rtd before swcarpentry did the same on their end :-)

**Comment by klieret** [comment]
Ah, you're right, I didn't check the git lesson! Makes a lot of sense then :)

**Pull request merged**
