### PR TITLE
Update Python introduction, add classes

### PR DESCRIPTION
**Pull request by mayou36**
Some updates and added material for the Python introduction

### CODE REVIEW

**Comment by chrisburr** [comment]
Looks like a nice addition, I'll take a deeper look soon.

For the tests to pass these new pages need to be added to the table of contents in `python/README.md`.

**Comment by mayou36** [comment]
Okey, let me add a few more things then, WIP

**Comment by mayou36** [comment]
This can be merged from my side. The class tutorial could surely be extended, however it is meant as an introduction/motivation for classes (currently).

**Comment by mayou36** [comment]
opened #19

**Pull request closed without merging**
