### PR TITLE
update environment

### PR DESCRIPTION
**Pull request by goi42**
Provides a few improvements:

- Updates CONTRIBUTING to refer to environment.yml instead of listing packages
- Adds starterkit-ci to environment.yml
- Renames environment to `analysis-essentials`

### CODE REVIEW

**Comment by jonas-eschle** [comment]
I've added the explicit command to create the conda env from the file. Just to confirm, did you check if the name old env name has not been used anywhere else?

**Comment by goi42** [comment]
@jonas-eschle Yes, I checked. I didn't see `example-environment` anywhere else.

**Review by jonas-eschle — APPROVED** [review]
Good for me then (assuming you agree on my addition)

**Comment by goi42** [comment]
@jonas-eschle Sorry, yes, thank you for making it more explicit.

**Pull request merged**
